### ISSUE TITLE
Transport hardcoded as cli

### ISSUE THREAD

**Issue by glennsb** [arista-eosplus/ansible-eos-interfaces#11]
Even with specifying eapi as the transport in the ```provider``` dictionary.

It seems maybe the hardcoded entries of ```transport: cli``` in all the eos_* modules override that.

This makes me sad to not be able to use the api, especially since right now my paramiko is all about not working because of no acceptable  kex algo

This was with a fresh install of the role with ansible v2.2.1.0

**Comment by dathelen** [comment]
Thanks for opening this issue!  We will have a review at our weekly Ansible meeting and back on this and your subsequent pull request
